services:
  influxdb3:
    image: quay.io/influxdb/influxdb3-core:latest
    container_name: influxdb3-core
    command: >
      serve
      --node-id=local-pc
      --object-store file
      --data-dir /var/lib/influxdb3
    ports:
      - "8181:8181"
    volumes:
      - influxdb3-data:/var/lib/influxdb3
    networks:
      - app-network
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - app-network
    restart: unless-stopped

  langgraph:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${ENV}
    container_name: langgraph-app
    ports:
      - "2024:2024"
    depends_on:
      - influxdb3
      - ollama
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    networks:
      - app-network
    restart: unless-stopped

  postgres:
    container_name: postgres-sql
    image: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

volumes:
  influxdb3-data:
  ollama-data:
  postgres-data:

networks:
  app-network:
    driver: bridge
