# Attach volumes for dev environment

x-airflow-volumes: &test-volumes
  volumes:
    - ./tests:/app/tests
    - ./pytest.ini:/app/pytest.ini
    - ./resources/data:/app/resources/data
    - ./langgraph.json:/app/langgraph.json

services:
  langgraph:
    <<: *test-volumes
