name: Pre-commit

on:
  pull_request:
  merge_group:
    types: [checks_requested]

jobs:
  lint:
    name: Pre-commit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Cache pre-commit environment
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            **/*.py

      - name: Run pre-commit
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          pre-commit run --files ${{ steps.changed-files.outputs.all_changed_files }} --show-diff-on-failure
